### ISSUE TITLE
Blockscout compat tracking

### ISSUE THREAD

**Issue by jsoares** [consensus-shipyard/fendermint#399]
Blockscout no longer fails the initial fetch if using #395. It can now get a list of blocks and starts fetching them in batches, as well as subscribing to new blocks. This means, of course, new issues -- which seem rather uniform across the different RPC flavours.

1. Timestamps

```
backend                         | 2023-11-06T23:17:32.840 application=explorer [info] tx/per day chart: collect records for txs per day stats
backend                         | 2023-11-06T23:17:32.840 application=explorer [info] tx/per day chart: earliest date 2023-11-05 00:00:00Z
backend                         | 2023-11-06T23:17:32.840 application=explorer [info] tx/per day chart: latest date 2023-11-05 23:59:59Z
backend                         | 2023-11-06T23:17:32.847 application=explorer [info] tx/per day chart: timestamp cannot be converted to min/max blocks, trying to find min/max blocks through a fallback option}
backend                         | 2023-11-06T23:17:32.850 application=explorer [warning] tx/per day chart: failed to get min/max blocks through a fallback option}
```

This is just a warning and doesn't seem to block anything. Also unclear whether it is related to our stack, maybe just normal init? I guess it should be doing something based on genesis and round period, so might even be configuration.

2. no pending_transaction/getPendingTransaction method available (ref: https://github.com/blockscout/blockscout/blob/master/apps/indexer/lib/indexer/fetcher/pending_transaction.ex)

```
backend                         | 2023-11-06T23:19:04.093 application=indexer fetcher=pending_transaction [error] %{code: -32601, message: "Method not found"}
```

This seems medium (pending transaction fetch can be disabled with INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER) and happens for most flavours. We may need to implement it.

3. Blocks fail to validate on account of blank nonce

```
backend                         | 2023-11-06T23:19:03.281 application=indexer fetcher=block_realtime block_number=248 step=import [error] failed to validate for block 248: [#Ecto.Changeset<action: nil, changes: %{base_fee_per_gas: #Explorer.Chain.Wei<1000>, consensus: true, difficulty: Decimal.new("0"), gas_limit: Decimal.new("0"), gas_used: Decimal.new("0"), hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<102, 254, 183, 14, 211, 38, 89, 200, 182, 150, 140, 26, 62, 204, 38, 166, 175, 74, 37, 10, 134, 116, 166, 124, 51, 156, 110, 217, 230, 152, 247, 189>>}, miner_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<253, 24, 72, 112, 111, 92, 27, 107, 41, 27, 33, 150, 74, 145, 41, 2, 103, 76, 119, 245>>}, number: 248, parent_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<183, 174, 73, 52, 16, 125, 238, 243, 132, 92, 29, 37, 99, 87, 204, 129, 69, 57, 102, 134, 158, 131, 207, 29, 71, 149, 217, 97, 75, 217, 227, 244>>}, size: 0, timestamp: ~U[2023-11-06 23:18:41.000000Z]}, errors: [nonce: {"can't be blank", [validation: :required]}], data: #Explorer.Chain.Block<>, valid?: false>].  Block will be retried by catchup indexer.
```

This seems critical.

**Comment by jsoares** [comment]
#401 resolves the issue with block parsing. Now Blockscout catches up to the current chain just fine, though the frontend still doesn't work. However, once a simple transaction gets sent, we get a parsing error on an infinite loop:

```
backend                         | 2023-11-07T14:36:30.208 application=indexer fetcher=block_catchup first_block_number=2499 last_block_number=0 missing_block_count=2 shrunk=false [info] Index had to catch up.
backend                         | 2023-11-07T14:36:30.208 application=indexer fetcher=block_catchup [info] Checking if index needs to catch up in 2500ms.
backend                         | 2023-11-07T14:36:32.717 application=indexer fetcher=block_catchup first_block_number=2499 last_block_number=2499 [error] ** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Transaction.elixir_to_params/1
backend                         |     (ethereum_jsonrpc 5.3.1) lib/ethereum_jsonrpc/transaction.ex:173: EthereumJSONRPC.Transaction.elixir_to_params(%{nil => nil, "blockHash" => nil, "blockNumber" => nil, "chainId" => 3522868364964899, "from" => "0xea335cf34c43057e712d508ffefbefeeec8ca2f4", "gas" => 1622716, "hash" => "0x2fd2f66b2cdb7ca6f5450284488d02016352ecb8cc89cac221e4a6ae67ba440a", "input" => "0x40", "maxFeePerGas" => 1500001200, "maxPriorityFeePerGas" => 1500000000, "nonce" => 0, "r" => 41576521057002916523900352016698720561307928786272745245160977851644718235989, "s" => 3053288900960943322918837341226170942799118998614669133035559477722027125401, "to" => "0xea335cf34c43057e712d508ffefbefeeec8ca2f4", "transactionIndex" => 0, "v" => 1, "value" => 10000000000000000000})
backend                         |     (elixir 1.14.5) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
backend                         |     (ethereum_jsonrpc 5.3.1) lib/ethereum_jsonrpc/blocks.ex:54: EthereumJSONRPC.Blocks.from_responses/2
backend                         |     (ethereum_jsonrpc 5.3.1) lib/ethereum_jsonrpc.ex:584: EthereumJSONRPC.fetch_blocks_by_params/3
backend                         |     (stdlib 3.17) timer.erl:166: :timer.tc/1
backend                         |     (indexer 5.3.1) lib/indexer/block/fetcher.ex:129: Indexer.Block.Fetcher.fetch_and_import_range/2
backend                         |     (stdlib 3.17) timer.erl:166: :timer.tc/1
backend                         |     (indexer 5.3.1) lib/indexer/block/catchup/fetcher.ex:195: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
backend                         | 
```

Looking at https://github.com/blockscout/blockscout/blob/1e832d995cc71b3b66b8fc6d51d5273924c1bbba/apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transaction.ex#L173, this seems to be trying to match one of the `elixir_to_params` clauses in the file, but we're a bit off from all of them. Specifically, we have these parameters:

```
nil => nil, 
"blockHash" => nil, 
"blockNumber" => nil, 
"chainId" => 3522868364964899, 
"from" => "0xea335cf34c43057e712d508ffefbefeeec8ca2f4", 
"gas" => 1622716, 
"hash" => "0x2fd2f66b2cdb7ca6f5450284488d02016352ecb8cc89cac221e4a6ae67ba440a", 
"input" => "0x40", 
"maxFeePerGas" => 1500001200, 
"maxPriorityFeePerGas" => 1500000000, 
"nonce" => 0, 
"r" => 41576521057002916523900352016698720561307928786272745245160977851644718235989, 
"s" => 3053288900960943322918837341226170942799118998614669133035559477722027125401, 
"to" => "0xea335cf34c43057e712d508ffefbefeeec8ca2f4", 
"transactionIndex" => 0, 
"v" => 1, 
"value" => 10000000000000000000
```

Also, that `nil => nil` looks shady.

cc @aakoshh

**Comment by jsoares** [comment]
Beyond pending transactions and internal transactions tracking, blockscout is now working after #414 #403 #401 #395
